name: Backfill product qty
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    # Use the PUBLIC DB URL for GitHub-hosted runners
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Quick sanity check that the DB host is reachable
      - name: DB ping
        run: |
          set -euo pipefail
          sudo apt-get update && sudo apt-get install -y postgresql-client
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\conninfo"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "SELECT now();"

      # Ensure required columns exist (idempotent)
      - name: Ensure qty columns exist
        run: |
          set -euo pipefail
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
          BEGIN;
          ALTER TABLE public.products
            ADD COLUMN IF NOT EXISTS pack_pattern TEXT,
            ADD COLUMN IF NOT EXISTS net_qty NUMERIC,
            ADD COLUMN IF NOT EXISTS net_unit TEXT,
            ADD COLUMN IF NOT EXISTS pack_count INTEGER;
          DO $$
          BEGIN
            IF NOT EXISTS (
              SELECT 1 FROM pg_constraint WHERE conname = 'products_net_unit_chk'
            ) THEN
              ALTER TABLE public.products
                ADD CONSTRAINT products_net_unit_chk CHECK (net_unit IN ('g','ml'));
            END IF;
          END$$;
          CREATE INDEX IF NOT EXISTS idx_products_net ON public.products (net_unit, net_qty);
          COMMIT;
          SQL
          # Optional: show the columns to confirm
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\d+ public.products"

      - name: Install deps
        run: pip install asyncpg

      - name: Run backfill script
        run: python scripts/backfill_qty.py
