name: Seed Coop physical stores (one-time)

on:
  workflow_dispatch:

jobs:
  seed-coop-stores:
    runs-on: ubuntu-latest
    concurrency:
      group: coop-seed-stores
      cancel-in-progress: false

    env:
      LANG: C.UTF-8
      PYTHONUNBUFFERED: "1"

      # Single connection string
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}

      # Optional discrete vars (if your script expects them)
      PGHOST:     ${{ secrets.PGHOST }}
      PGPORT:     ${{ secrets.PGPORT }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER:     ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests beautifulsoup4 lxml psycopg2-binary || true

      - name: Run Coop store scraper
        run: |
          python scripts/scrape_coop_stores.py
