name: "Coop – Category Crawl (Playwright) + optional DB upsert"

on:
  workflow_dispatch:
    inputs:
      region:
        description: "Base region URL (e.g., https://coophaapsalu.ee or https://vandra.ecoop.ee)"
        required: false
        default: "https://vandra.ecoop.ee"
      categories_multiline:
        description: "Category URLs or paths (one per line). e.g. /et/tooted/53-joogid"
        required: false
        default: ""
      categories_file_url:
        description: "Optional raw URL to a .txt file with categories (one per line)"
        required: false
        default: ""
      page_limit:
        description: "Discovery cap per category (0 = all)"
        required: false
        default: "0"
      max_products:
        description: "Post-discovery cap per category (0 = all)"
        required: false
        default: "0"
      headless:
        description: "Chromium headless (1/0)"
        required: false
        default: "1"
      req_delay:
        description: "Delay between actions (seconds)"
        required: false
        default: "0.5"
      pdp_workers:
        description: "Concurrent PDP tabs per category"
        required: false
        default: "4"
      upsert_db:
        description: "Set to 1 to upsert into public.staging_coop_products"
        required: false
        default: "0"

  # 05:30 Tallinn daily (02:30 UTC; GH cron runs in UTC)
  schedule:
    - cron: "30 2 * * *"

concurrency:
  group: coop-scrape-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: false

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.46.0 asyncpg
          python -m playwright install --with-deps chromium

      - name: Run Coop crawler
        env:
          # Auto-upsert on schedule; manual runs use the input toggle
          COOP_UPSERT_DB: ${{ github.event_name == 'schedule' && '1' || inputs.upsert_db }}
          DATABASE_URL: ${{ (github.event_name == 'schedule' || inputs.upsert_db == '1') && secrets.DATABASE_URL || '' }}
          CATS_MULTILINE: ${{ inputs.categories_multiline }}
          CATS_FILE_URL: ${{ inputs.categories_file_url }}
          REGION_URL: ${{ inputs.region }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out

          CATS_ALL="coop_categories.txt"
          : > "$CATS_ALL"

          # 1) If a categories file URL is provided, download & append
          if [ -n "$CATS_FILE_URL" ]; then
            echo ">> downloading categories file: $CATS_FILE_URL"
            curl -fsSL "$CATS_FILE_URL" >> "$CATS_ALL" || true
            echo >> "$CATS_ALL"
          fi

          # 2) If multiline categories were provided, append them safely
          if [ -n "$CATS_MULTILINE" ]; then
            printf '%s\n' "$CATS_MULTILINE" >> "$CATS_ALL"
            echo >> "$CATS_ALL"
          fi

          # 3) If still empty, supply sensible defaults by region
          if [ ! -s "$CATS_ALL" ]; then
            echo ">> no categories provided; applying defaults for region: $REGION_URL"
            if echo "$REGION_URL" | grep -qi 'vandra\.ecoop\.ee'; then
              cat >> "$CATS_ALL" <<'__DEF_VANDRA__'
/et/tooted/1-puu-ja-koogiviljad
/et/tooted/6-liha-ja-kalatooted
/et/tooted/20-piimatooted-munad-voi
/et/tooted/30-kuivained-kastmed
/et/tooted/39-valmistoit
/et/tooted/47-pagaritooted
/et/tooted/53-joogid
/et/tooted/69-snakid-ja-maiustused
/et/tooted/214937-sugavkulmutatud-toidud
/et/tooted/78-beebitooted
/et/tooted/81-ilu-ja-hugieenitooted/214978-intiimhugieen
/et/tooted/93-kodutarbed/94-pesupesemis-ja-hooldustooted
/et/tooted/93-kodutarbed/95-puhastusvahendid-ja-varskendajad
/et/tooted/93-kodutarbed/97-koristustarbed
/et/tooted/93-kodutarbed/98-pehme-paber
/et/tooted/93-kodutarbed/99-kupsetamine-sailitamine-filtrid
/et/tooted/109-lemmikloomakaubad/76053-kassitoidud
/et/tooted/109-lemmikloomakaubad/76054-koeratoidud
/et/tooted/113-coop-omamargi-tooted
__DEF_VANDRA__
            elif echo "$REGION_URL" | grep -qi 'coophaapsalu\.ee'; then
              cat >> "$CATS_ALL" <<'__DEF_HAAPSALU__'
/tootekategooria/kulmutatud-toidukaubad/
/tootekategooria/puu-ja-koogivili/
/tootekategooria/liha-ja-kalatooted/
/tootekategooria/piimatooted-munad-void/
/tootekategooria/valmistoit/
/tootekategooria/pagaritooted/
/tootekategooria/purgitoit/
/tootekategooria/kuivained-kastmed/
/tootekategooria/maiustused-snakid/
/tootekategooria/eritooted/
/tootekategooria/joogid/
/tootekategooria/alkohoolsed-joogid/
/tootekategooria/beebitooted/
/tootekategooria/hugieenitarbed/suuhugieenikaubad/
/tootekategooria/hugieenitarbed/raseerimisvahendid/
/tootekategooria/hugieenitarbed/intiimhugieen-plaastrid/
/tootekategooria/kodutarbed/pesupesemise-ja-hooldustooted/
/tootekategooria/kodutarbed/puhastusvahendid-ohuvarskendajad/
/tootekategooria/kodutarbed/koristusvahendid/
/tootekategooria/kodutarbed/pehme-paber/
/tootekategooria/kodutarbed/kupsetus-sailitustooted-kohvifiltrid/
/tootekategooria/kodutarbed/noudepesuks/
/tootekategooria/lemmikloomakaubad/lemmikloomatoit/
/tootekategooria/lemmikloomakaubad/kassitoit/
__DEF_HAAPSALU__
            else
              echo "/et/tooted/53-joogid" >> "$CATS_ALL"
            fi
          fi

          # Normalize CRLF just in case
          sed -e 's/\r$//' -i "$CATS_ALL"

          # 4) Run crawler using the combined file
          python scripts/coop_crawl_categories_pw.py \
            --region "$REGION_URL" \
            --categories-multiline "" \
            --categories-file "$CATS_ALL" \
            --page-limit "${{ inputs.page_limit }}" \
            --max-products "${{ inputs.max_products }}" \
            --headless "${{ inputs.headless }}" \
            --req-delay "${{ inputs.req_delay }}" \
            --pdp-workers "${{ inputs.pdp_workers }}" \
            --out "out/coop_products_${{ github.run_id }}.csv"

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: coop-products-${{ github.run_id }}
          path: out/*.csv
          if-no-files-found: warn
          retention-days: 7
