name: Seed Coop physical stores (one-time)

on:
  workflow_dispatch:

jobs:
  seed-coop-stores:
    runs-on: ubuntu-latest
    concurrency:
      group: coop-seed-stores
      cancel-in-progress: false

    env:
      LANG: C.UTF-8
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}
      # Optional discrete PG vars if your code reads them:
      PGHOST:     ${{ secrets.PGHOST }}
      PGPORT:     ${{ secrets.PGPORT }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER:     ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure these are present even if not in requirements
          pip install playwright psycopg2-binary beautifulsoup4 lxml requests

      - name: Install Playwright browsers (Chromium) + Linux deps
        run: |
          python -m playwright install --with-deps chromium
        # If --with-deps isn't available for your version, use:
        # run: |
        #   python -m playwright install chromium
        #   sudo python -m playwright install-deps chromium

      - name: Run Coop store scraper
        run: |
          python scripts/scrape_coop_stores.py
