name: DB Views Migration (latest & cheapest)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "migrations/*.sql"
      - ".github/workflows/db-views-migration.yml"

jobs:
  migrate-views:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DATABASE_URL: ${{ secrets.RW_DATABASE_URL }}  # e.g. postgres://.../db?sslmode=require

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql --version

      - name: Apply migrations (all .sql, sorted)
        shell: bash
        run: |
          shopt -s nullglob
          files=(migrations/*.sql)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No migration files found in migrations/ — skipping."
            exit 0
          fi
          # Sort filenames to ensure deterministic order
          IFS=$'\n' files=($(sort <<<"${files[*]}")); unset IFS
          for f in "${files[@]}"; do
            echo "Applying: $f"
            psql -X "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
          done

      - name: Smoke test
        run: |
          echo "List views:" && psql -X "$DATABASE_URL" -c '\dv' || true
          echo "Sample latest-store prices:" && \
            psql -X "$DATABASE_URL" -c "SELECT * FROM public.v_latest_store_prices LIMIT 5;" || true
          echo "Sample cheapest-offer:" && \
            psql -X "$DATABASE_URL" -c "SELECT * FROM public.v_cheapest_offer LIMIT 5;" || true
