name: "Export ALL products for Barbora matching"

on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}   # same secret you use for other exports
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      # Helper: a tiny SQL macro so we don't repeat ourselves
      - name: Export Selver
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT DISTINCT
              p.id,
              p.name,
              COALESCE(NULLIF(trim(p.brand),''),'') AS brand,
              COALESCE(NULLIF(trim(p.ean),''),'')   AS ean,
              COALESCE(NULLIF(trim(p.size_text),''),'') AS size_text
            FROM prices pr
            JOIN stores   s ON s.id = pr.store_id
            JOIN products p ON p.id = pr.product_id
            WHERE s.chain ILIKE 'selver%'
          ) TO STDOUT WITH CSV HEADER" > selver_products.csv

      - name: Export Prisma
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT DISTINCT
              p.id,
              p.name,
              COALESCE(NULLIF(trim(p.brand),''),'') AS brand,
              COALESCE(NULLIF(trim(p.ean),''),'')   AS ean,
              COALESCE(NULLIF(trim(p.size_text),''),'') AS size_text
            FROM prices pr
            JOIN stores   s ON s.id = pr.store_id
            JOIN products p ON p.id = pr.product_id
            WHERE s.chain ILIKE 'prisma%'
          ) TO STDOUT WITH CSV HEADER" > prisma_products.csv

      - name: Export Rimi
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT DISTINCT
              p.id,
              p.name,
              COALESCE(NULLIF(trim(p.brand),''),'') AS brand,
              COALESCE(NULLIF(trim(p.ean),''),'')   AS ean,
              COALESCE(NULLIF(trim(p.size_text),''),'') AS size_text
            FROM prices pr
            JOIN stores   s ON s.id = pr.store_id
            JOIN products p ON p.id = pr.product_id
            WHERE s.chain ILIKE 'rimi%'
          ) TO STDOUT WITH CSV HEADER" > rimi_products.csv

      - name: Export Barbora
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT DISTINCT
              p.id,
              p.name,
              COALESCE(NULLIF(trim(p.brand),''),'') AS brand,
              COALESCE(NULLIF(trim(p.ean),''),'')   AS ean,
              COALESCE(NULLIF(trim(p.size_text),''),'') AS size_text
            FROM prices pr
            JOIN stores   s ON s.id = pr.store_id
            JOIN products p ON p.id = pr.product_id
            WHERE s.chain ILIKE 'barbora%'
          ) TO STDOUT WITH CSV HEADER" > barbora_products.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exports-all-four-chains
          path: |
            selver_products.csv
            prisma_products.csv
            rimi_products.csv
            barbora_products.csv
