name: "Export products for matching (with amount, no index build)"

on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Export Selver
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "SET lock_timeout='5s'; SET statement_timeout='45min';" \
           -c "\copy (
            SELECT
              p.id,
              p.name,
              COALESCE(p.brand,'')       AS brand,
              COALESCE(p.ean,'')         AS ean,
              COALESCE(p.size_text,'')   AS size_text,
              COALESCE(p.amount,'')      AS amount
            FROM products p
            WHERE EXISTS (
              SELECT 1
              FROM prices pr
              JOIN stores s ON s.id = pr.store_id
              WHERE pr.product_id = p.id
                AND s.chain ILIKE 'selver%'
            )
          ) TO STDOUT WITH CSV HEADER" > selver_products.csv

      - name: Export Prisma
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "SET lock_timeout='5s'; SET statement_timeout='45min';" \
           -c "\copy (
            SELECT
              p.id,
              p.name,
              COALESCE(p.brand,'')       AS brand,
              COALESCE(p.ean,'')         AS ean,
              COALESCE(p.size_text,'')   AS size_text,
              COALESCE(p.amount,'')      AS amount
            FROM products p
            WHERE EXISTS (
              SELECT 1
              FROM prices pr
              JOIN stores s ON s.id = pr.store_id
              WHERE pr.product_id = p.id
                AND s.chain ILIKE 'prisma%'
            )
          ) TO STDOUT WITH CSV HEADER" > prisma_products.csv

      - name: Export Rimi
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "SET lock_timeout='5s'; SET statement_timeout='45min';" \
           -c "\copy (
            SELECT
              p.id,
              p.name,
              COALESCE(p.brand,'')       AS brand,
              COALESCE(p.ean,'')         AS ean,
              COALESCE(p.size_text,'')   AS size_text,
              COALESCE(p.amount,'')      AS amount
            FROM products p
            WHERE EXISTS (
              SELECT 1
              FROM prices pr
              JOIN stores s ON s.id = pr.store_id
              WHERE pr.product_id = p.id
                AND s.chain ILIKE 'rimi%'
            )
          ) TO STDOUT WITH CSV HEADER" > rimi_products.csv

      - name: Export Barbora
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "SET lock_timeout='5s'; SET statement_timeout='45min';" \
           -c "\copy (
            SELECT
              p.id,
              p.name,
              COALESCE(p.brand,'')       AS brand,
              COALESCE(p.ean,'')         AS ean,
              COALESCE(p.size_text,'')   AS size_text,
              COALESCE(p.amount,'')      AS amount
            FROM products p
            WHERE EXISTS (
              SELECT 1
              FROM prices pr
              JOIN stores s ON s.id = pr.store_id
              WHERE pr.product_id = p.id
                AND s.chain ILIKE 'barbora%'
            )
          ) TO STDOUT WITH CSV HEADER" > barbora_products.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: export-products-for-matching
          path: |
            selver_products.csv
            prisma_products.csv
            rimi_products.csv
            barbora_products.csv
