name: Export products for matching

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}  # external/public URL

    steps:
      - uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Preflight (DNS + connect)
        run: |
          set -euo pipefail
          echo "Host:" "$(echo "$DATABASE_URL" | sed -E 's|.*@([^:/?]+).*|\1|')"
          dig +short maglev.proxy.rlwy.net || true
          PGPASSWORD='' psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c 'SELECT 1;'

      - name: Export Selver (online store only)
        shell: bash
        run: |
          set -euo pipefail
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT p.id, p.name, p.brand, p.ean, p.size_text, p.amount
            FROM products p
            JOIN prices pr ON pr.product_id = p.id
            JOIN stores s  ON s.id = pr.store_id
            WHERE s.name ILIKE '%e-Selver%' OR s.name ILIKE '%Selver e-%'
            GROUP BY p.id, p.name, p.brand, p.ean, p.size_text, p.amount
          ) TO 'selver_products.csv' WITH CSV HEADER;"
      
      - name: Export Prisma (Prisma Online (Tallinn))
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT p.id, p.name, p.brand, p.ean, p.size_text, p.amount
            FROM products p
            JOIN prices pr ON pr.product_id = p.id
            JOIN stores s  ON s.id = pr.store_id
            WHERE s.name ILIKE '%Prisma Online (Tallinn)%'
            GROUP BY p.id, p.name, p.brand, p.ean, p.size_text, p.amount
          ) TO 'prisma_products.csv' WITH CSV HEADER;"

      - name: Export Rimi (Rimi ePood)
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT p.id, p.name, p.brand, p.ean, p.size_text, p.amount
            FROM products p
            JOIN prices pr ON pr.product_id = p.id
            JOIN stores s  ON s.id = pr.store_id
            WHERE s.name ILIKE '%Rimi ePood%'
            GROUP BY p.id, p.name, p.brand, p.ean, p.size_text, p.amount
          ) TO 'rimi_products.csv' WITH CSV HEADER;"

      - name: Export Barbora (Barbora ePood / Maxima)
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "\copy (
            SELECT p.id, p.name, p.brand, p.ean, p.size_text, p.amount
            FROM products p
            JOIN prices pr ON pr.product_id = p.id
            JOIN stores s  ON s.id = pr.store_id
            WHERE s.name ILIKE '%Barbora ePood%' OR s.chain ILIKE '%Maxima%'
            GROUP BY p.id, p.name, p.brand, p.ean, p.size_text, p.amount
          ) TO 'barbora_products.csv' WITH CSV HEADER;"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: products-for-matching
          path: |
            selver_products.csv
            prisma_products.csv
            rimi_products.csv
            barbora_products.csv
