name: Export Coop products (EAN-safe CSV)

on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          mkdir -p out

      # --- Haapsalu (has EANs) ---
      - name: Export coophaapsalu.ee
        run: |
          psql "$DATABASE_URL" <<'SQL'
          \t on
          \pset footer off
          \copy (
            SELECT
              chain,
              channel,
              store_host,
              city_path,
              category_name,
              ext_id,
              name,
              brand,
              manufacturer,
              size_text,
              price,
              currency,
              description,
              image_url,
              url,
              scraped_at,
              ean_raw::text AS ean_raw
            FROM staging_coop_products
            WHERE store_host = 'coophaapsalu.ee'
            ORDER BY lower(name)
          ) TO 'out/coop_coophaapsalu.ee.csv' WITH (FORMAT csv, HEADER true, QUOTE '"', FORCE_QUOTE *);
          SQL

      # --- Vändra (mostly missing EANs) ---
      - name: Export vandra.ecoop.ee
        run: |
          psql "$DATABASE_URL" <<'SQL'
          \t on
          \pset footer off
          \copy (
            SELECT
              chain,
              channel,
              store_host,
              city_path,
              category_name,
              ext_id,
              name,
              brand,
              manufacturer,
              size_text,
              price,
              currency,
              description,
              image_url,
              url,
              scraped_at,
              ean_raw::text AS ean_raw
            FROM staging_coop_products
            WHERE store_host = 'vandra.ecoop.ee'
            ORDER BY lower(name)
          ) TO 'out/coop_vandra.ecoop.ee.csv' WITH (FORMAT csv, HEADER true, QUOTE '"', FORCE_QUOTE *);
          SQL

      - name: Upload CSVs
        uses: actions/upload-artifact@v4
        with:
          name: coop-vandra-haapsalu-exports
          path: out/*.csv
          if-no-files-found: error
          retention-days: 14
