name: Export Coop products (EAN-safe CSV)

on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          mkdir -p "$GITHUB_WORKSPACE/out"

      - name: Preflight DB check (row counts)
        run: |
          set -euo pipefail
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
            SELECT store_host, COUNT(*) AS rows,
                   SUM((ean_raw ~ '^[0-9]+$' AND length(ean_raw) IN (8,12,13,14))::int) AS with_valid_ean
            FROM staging_coop_products
            WHERE store_host IN ('coophaapsalu.ee','vandra.ecoop.ee')
            GROUP BY store_host
            ORDER BY store_host;
          "

      - name: Export coophaapsalu.ee
        run: |
          set -euo pipefail
          OUT="$GITHUB_WORKSPACE/out/coop_coophaapsalu.ee.csv"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<SQL
          \set ON_ERROR_STOP on
          \t on
          \pset footer off
          \echo Exporting coophaapsalu.ee to :OUT
          \copy (
            SELECT
              chain,
              channel,
              store_host,
              city_path,
              category_name,
              ext_id,
              name,
              brand,
              manufacturer,
              size_text,
              price,
              currency,
              description,
              image_url,
              url,
              scraped_at,
              ean_raw::text AS ean_raw
            FROM staging_coop_products
            WHERE store_host = 'coophaapsalu.ee'
            ORDER BY lower(name)
          ) TO :'OUT' WITH (FORMAT csv, HEADER true, QUOTE '"', FORCE_QUOTE *);
          SQL
          echo "Preview coophaapsalu.ee:"
          wc -l "$OUT" || true
          head -n 3 "$OUT" || true

      - name: Export vandra.ecoop.ee
        run: |
          set -euo pipefail
          OUT="$GITHUB_WORKSPACE/out/coop_vandra.ecoop.ee.csv"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<SQL
          \set ON_ERROR_STOP on
          \t on
          \pset footer off
          \echo Exporting vandra.ecoop.ee to :OUT
          \copy (
            SELECT
              chain,
              channel,
              store_host,
              city_path,
              category_name,
              ext_id,
              name,
              brand,
              manufacturer,
              size_text,
              price,
              currency,
              description,
              image_url,
              url,
              scraped_at,
              ean_raw::text AS ean_raw
            FROM staging_coop_products
            WHERE store_host = 'vandra.ecoop.ee'
            ORDER BY lower(name)
          ) TO :'OUT' WITH (FORMAT csv, HEADER true, QUOTE '"', FORCE_QUOTE *);
          SQL
          echo "Preview vandra.ecoop.ee:"
          wc -l "$OUT" || true
          head -n 3 "$OUT" || true

      - name: List output dir
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -lah "$GITHUB_WORKSPACE/out" || true

      - name: Upload CSVs
        uses: actions/upload-artifact@v4
        with:
          name: coop-vandra-haapsalu-exports
          path: out/*.csv
          if-no-files-found: error
          retention-days: 14
