2s
2h 29m 15s
Run set -euo pipefail
Staggering start by 24s for store parnu...
Running wolt:coop-parnu (venueId=auto) → out/coop_wolt_18319642923_parnu.csv
[args] headless=1 req_delay=1.2 pdp_workers(not used)=4 goto=networkidle nav_timeout=60000ms store_host=wolt:coop-parnu probe_limit=250 modal_probe_limit=0 category_timeout=420.0s venue_id=(auto-discover) upsert_per_category=True flush_every=40
[out] streaming CSV → out/coop_wolt_18319642923_parnu.csv
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/soe-toit-3
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/soe-toit-3
[grid] anchors=3 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/puu-ja-koogiviljad-4
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/puu-ja-koogiviljad-4
[grid] anchors=11 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/puu-ja-koogiviljad-4
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/pagaritooted-9
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/pagaritooted-9
[grid] anchors=21 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kondiitritooted-13
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kondiitritooted-13
[grid] anchors=21 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/valmistoidud-14
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/valmistoidud-14
[grid] anchors=17 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/valmistoidud-14
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/piimatooted-19
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/piimatooted-19
[grid] anchors=17 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/piimatooted-19
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/jogurtid-piimamaiused-24
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/jogurtid-piimamaiused-24
[grid] anchors=44 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/jogurtid-piimamaiused-24
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/munad-30
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/munad-30
[grid] anchors=5 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/voi-ja-maarded-31
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/voi-ja-maarded-31
[grid] anchors=10 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/voi-ja-maarded-31
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/juustud-34
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/juustud-34
[grid] anchors=13 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/juustud-34
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/lihatooted-41
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/lihatooted-41
[grid] anchors=23 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/vorstid-singid-peekon-49
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/vorstid-singid-peekon-49
[grid] anchors=18 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/vorstid-singid-peekon-49
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kalatooted-54
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kalatooted-54
[grid] anchors=20 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/kalatooted-54
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/vegantooted-59
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/vegantooted-59
[grid] anchors=9 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/vegantooted-59
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kiired-eined-64
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kiired-eined-64
[grid] anchors=13 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/kiired-eined-64
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/maailmakook-67
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/maailmakook-67
[grid] anchors=20 json_blobs=12 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/hoidised-68
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/hoidised-68
[grid] anchors=8 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/hoidised-68
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kuivained-72
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kuivained-72
[grid] anchors=11 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/kuivained-72
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/maitseained-kupsetus-78
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/maitseained-kupsetus-78
[grid] anchors=10 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/maitseained-kupsetus-78
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kastmed-ja-olid-84
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kastmed-ja-olid-84
[grid] anchors=6 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kulmutatud-tooted-90
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kulmutatud-tooted-90
[grid] anchors=23 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/jaatised-97
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/jaatised-97
[grid] anchors=30 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/snakid-100
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/snakid-100
[grid] anchors=46 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kupsised-ja-vahvlid-105
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kupsised-ja-vahvlid-105
[grid] anchors=4 json_blobs=14 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/kupsised-ja-vahvlid-105
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/maiustused-109
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/maiustused-109
[grid] anchors=23 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kohv-tee-kakao-116
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kohv-tee-kakao-116
[grid] anchors=16 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/kohv-tee-kakao-116
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/vesi-120
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/vesi-120
[grid] anchors=24 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/mahlad-ja-smuutid-123
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/mahlad-ja-smuutid-123
[grid] anchors=8 json_blobs=14 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/mahlad-ja-smuutid-123
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/karastusjoogid-128
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/karastusjoogid-128
[grid] anchors=30 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/alkoholivabad-joogid-134
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/alkoholivabad-joogid-134
[grid] anchors=24 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/lahja-alkohol-135
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/lahja-alkohol-135
[grid] anchors=42 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/lahja-alkohol-135
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/veinid-140
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/veinid-140
[grid] anchors=12 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/veinid-140
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kange-alkohol-146
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kange-alkohol-146
[grid] anchors=4 json_blobs=14 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/kange-alkohol-146
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kassidele-156
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kassidele-156
[grid] anchors=34 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/koertele-157
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/koertele-157
[grid] anchors=27 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/beebitoidud-160
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/beebitoidud-160
[grid] anchors=34 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/mahkmed-161
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/mahkmed-161
[grid] anchors=11 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/suuhooldus-164
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/suuhooldus-164
[grid] anchors=15 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/kehahooldus-166
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/kehahooldus-166
[grid] anchors=16 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/raseerimine-170
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/raseerimine-170
[grid] anchors=8 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/intiimhugieen-171
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/intiimhugieen-171
[grid] anchors=13 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/majapidamiskaubad-174
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/majapidamiskaubad-174
[grid] anchors=23 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[warn] category watchdog timeout after 420.0s → skipping remainder of https://wolt.com/et/est/parnu/venue/coop-prnu/items/majapidamiskaubad-174
[cat-wolt] https://wolt.com/et/est/parnu/venue/coop-prnu/items/toiduvalmistamine-181
[info] forcing Playwright fallback for https://wolt.com/et/est/parnu/venue/coop-prnu/items/toiduvalmistamine-181
[grid] anchors=9 json_blobs=13 (after geolocation)
[info] venueId detected: 6282118831e5208be09e450f
[info] category rows: 0 (built=0 skipped=5) (pw-fallback)
[stats] rows=0  gtin_present=0  brand_or_manufacturer_present=0
[ok] CSV ready: out/coop_wolt_18319642923_parnu.csv
[info] No rows to upsert.
