name: Load test /compare

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Backend base URL (e.g. https://grocery-backend-production-66f0.up.railway.app)"
        required: true
      lat:
        description: "Latitude"
        required: true
      lon:
        description: "Longitude"
        required: true
      radius:
        description: "Radius km"
        default: "10"
      concurrency:
        description: "Concurrent requests"
        default: "2"
      requests:
        description: "Total requests"
        default: "50"
      items:
        description: "Items per basket"
        default: "12"
      target_rps:
        description: "Requests/second pacing (keeps under throttle)"
        default: "0.4"
      auth_bearer:
        description: "Bearer token (optional)"
        required: false
      max_errors:
        description: "Fail if errors > this number"
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --disable-pip-version-check httpx

      - name: Preflight checks
        env:
          BASE_URL: ${{ github.event.inputs.base_url }}
        run: |
          set -x
          echo "GET $BASE_URL/healthz"
          curl -sS -D - "$BASE_URL/healthz" || true
          echo
          echo "POST $BASE_URL/compare (tiny payload)"
          curl -sS -D - -H "Content-Type: application/json" \
            -X POST "$BASE_URL/compare" \
            --data '{"grocery_list":{"items":[{"product":"Milk","quantity":1}]},
                     "lat":59.43,"lon":24.75,"radius_km":2}' || true
          echo

      - name: Run load test
        env:
          PYTHONUNBUFFERED: "1"
          BASE_URL:    ${{ github.event.inputs.base_url }}
          LAT:         ${{ github.event.inputs.lat }}
          LON:         ${{ github.event.inputs.lon }}
          RADIUS:      ${{ github.event.inputs.radius }}
          CONCURRENCY: ${{ github.event.inputs.concurrency }}
          REQUESTS:    ${{ github.event.inputs.requests }}
          ITEMS:       ${{ github.event.inputs.items }}
          TARGET_RPS:  ${{ github.event.inputs.target_rps }}
          AUTH_BEARER: ${{ github.event.inputs.auth_bearer }}
        run: |
          mkdir -p out
          CMD="python scripts/loadtest_compare.py \
            --base-url \"$BASE_URL\" \
            --lat \"$LAT\" --lon \"$LON\" --radius \"$RADIUS\" \
            --concurrency \"$CONCURRENCY\" --requests \"$REQUESTS\" \
            --items \"$ITEMS\" --target-rps \"$TARGET_RPS\" \
            --out out/summary.json"
          if [ -n "$AUTH_BEARER" ]; then
            CMD="$CMD --auth-bearer \"$AUTH_BEARER\""
          fi
          echo "$CMD"
          bash -lc "$CMD" | tee out/run.log

      - name: Fail if too many errors
        env:
          MAX_ERRORS: ${{ github.event.inputs.max_errors }}
        run: |
          ERRORS=$(grep -oE 'Errors: [0-9]+' out/run.log | awk '{print $2}')
          ERRORS=${ERRORS:-0}
          echo "Errors: $ERRORS"
          if [ "$ERRORS" -gt "$MAX_ERRORS" ]; then
            echo "Too many errors ($ERRORS > $MAX_ERRORS)"
            exit 1
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compare-loadtest
          path: out/
