name: Load test /compare

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "https://grocery-backend-production-66f0.up.railway.app"
        required: true
      lat:
        description: "59.34146"
        required: true
      lon:
        description: "24.61468"
        required: true
      radius:
        description: "Radius km"
        default: "10"
      concurrency:
        description: "Concurrent requests"
        default: "2"
      requests:
        description: "Total requests"
        default: "50"
      items:
        description: "Items per basket"
        default: "12"
      target_rps:
        description: "Requests/second pacing (keeps under throttle)"
        default: "0.4"
      auth_bearer:
        description: "Bearer token (optional)"
        required: false
      products_file:
        description: "Path to product list in repo (optional)"
        required: false
      max_errors:
        description: "Fail if errors > this number"
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install httpx

      - name: Run load test
        run: |
          mkdir -p out
          CMD="python scripts/loadtest_compare.py \
            --base-url '${{ inputs.base_url }}' \
            --lat '${{ inputs.lat }}' --lon '${{ inputs.lon }}' --radius '${{ inputs.radius }}' \
            --concurrency '${{ inputs.concurrency }}' --requests '${{ inputs.requests }}' \
            --items '${{ inputs.items }}' --target-rps '${{ inputs.target_rps }}' \
            --out out/summary.json"
          if [ -n "${{ inputs.auth_bearer }}" ]; then
            CMD="$CMD --auth-bearer '${{ inputs.auth_bearer }}'"
          fi
          if [ -n "${{ inputs.products_file }}" ]; then
            CMD="$CMD --products-file '${{ inputs.products_file }}'"
          fi
          echo "$CMD"
          bash -lc "$CMD" | tee out/run.log

      - name: Fail if too many errors
        run: |
          ERRORS=$(grep -oE 'Errors: [0-9]+' out/run.log | awk '{print $2}')
          ERRORS=${ERRORS:-0}
          echo "Errors: $ERRORS"
          if [ "$ERRORS" -gt "${{ inputs.max_errors }}" ]; then
            echo "Too many errors ($ERRORS > ${{ inputs.max_errors }})"
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: compare-loadtest
          path: out/
