name: Prisma → Price Update (every 2 hours)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours (UTC)

concurrency:
  group: prisma-price-update
  cancel-in-progress: true

jobs:
  update-prices:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      DATABASE_URL: ${{ secrets.RW_DATABASE_URL }}
      PRISMA_STORE_ID: "14"
      PRICE_CURRENCY: "EUR"
      PRICE_TYPE: "regular"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install playwright psycopg2-binary

      - name: Install Chromium + deps
        run: python -m playwright install --with-deps chromium

      # optional warm-up on 5 items (quick sanity before the big run)
      - name: Smoke test (5)
        run: python scripts/prisma_price_updater.py --max-products 5 --headless 1

      - name: Update Prisma prices (batch 1000)
        run: python scripts/prisma_price_updater.py --max-products 1000 --headless 1
