jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PRODUCTS_TABLE: products   # be explicit

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install playwright psycopg2-binary

      # IMPORTANT: install browser WITH system deps
      - name: Install Chromium + deps
        run: python -m playwright install --with-deps chromium

      # Debug: show which DB the runner is connected to
      - name: Debug DB identity
        run: |
          python - <<'PY'
          import os, psycopg2
          conn = psycopg2.connect(os.environ["DATABASE_URL"])
          cur = conn.cursor()
          cur.execute("SELECT current_database(), inet_server_addr();")
          print("DB identity:", cur.fetchone())
          PY

      - name: Run Prisma → DB
        run: python scripts/prisma_food_scrape_to_db.py --max-products 400 --headless 1

      - name: Produce CSV export
        run: python scripts/prisma_food_scraper.py --out prisma_foods.csv --max-products 400 --headless 1

      - name: Preview CSV size
        run: |
          wc -l prisma_foods.csv || true
          head -n 5 prisma_foods.csv || true

      - uses
