name: Prisma → DB Scrape + CSV Artifact

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 23 * * *"   # ~02:00 Tallinn

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PRODUCTS_TABLE: products

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install playwright psycopg2-binary

      - name: Install Chromium + deps
        run: python -m playwright install --with-deps chromium

      # ---- DIAGNOSTICS -------------------------------------
