name: Prisma → DB Scrape + CSV Artifact

on:
  workflow_dispatch: {}
  schedule:
    # 02:00 Tallinn ≈ 23:00 UTC during summer (UTC+3)
    - cron: "0 23 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install playwright psycopg2-binary

      - name: Install Chromium for Playwright
        run: python -m playwright install chromium

      # 1) Run the DB upsert (writes straight into Railway Postgres)
      - name: Run Prisma → DB
        run: |
          python scripts/prisma_food_scrape_to_db.py --max-products 1000 --headless 1

      # 2) Run the CSV scraper to also produce a CSV file for download
      - name: Produce CSV export
        run: |
          python scripts/prisma_food_scraper.py --out prisma_foods.csv --max-products 1000 --headless 1
          echo "CSV rows:" $(grep -c '^' prisma_foods.csv)

      # 3) Upload CSV artifact
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: prisma_foods.csv
          path: prisma_foods.csv
          if-no-files-found: error
