name: Prisma → DB Scrape + CSV Artifact

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 23 * * *"   # ~02:00 Tallinn

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      # Use the Railway DB secret you created
      DATABASE_URL: ${{ secrets.RW_DATABASE_URL }}
      PRODUCTS_TABLE: products
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install playwright psycopg2-binary

      - name: Install Chromium + deps
        run: python -m playwright install --with-deps chromium

      # Diagnostics (prints DB host/db so we know we're hitting the right one)
      - name: Assert DATABASE_URL & connect
        shell: bash
        run: |
          python - <<'PY'
          import os, sys, urllib.parse, psycopg2
          url = os.getenv("DATABASE_URL")
          if not url:
            print("ERROR: DATABASE_URL secret is missing."); sys.exit(2)
          p = urllib.parse.urlparse(url)
          print("DATABASE_URL host:", p.hostname, "db:", p.path.lstrip('/'))
          if p.hostname and "supabase.co" in p.hostname:
            print("ERROR: DATABASE_URL still points to Supabase. Update RW_DATABASE_URL to Railway."); sys.exit(2)
          try:
            conn = psycopg2.connect(url)
            cur = conn.cursor()
            cur.execute("SELECT current_database(), inet_server_addr();")
            print("DB identity:", cur.fetchone(
