name: Prisma → DB Scrape + CSV Artifact

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 23 * * *"   # ~02:00 Tallinn

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      DATABASE_URL: ${{ secrets.RW_DATABASE_URL }}   # Railway URL secret
      PRODUCTS_TABLE: products
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install playwright psycopg2-binary

      - name: Install Chromium + deps
        run: python -m playwright install --with-deps chromium

      # --- Diagnostics: verify the secret and DB connectivity (no heredoc) ---
      - name: Print DATABASE_URL host/db
        run: |
          python -c "import os,urllib.parse as u; x=u.urlparse(os.environ['DATABASE_URL']); print('DATABASE_URL host:', x.hostname, 'db:', x.path.lstrip('/'))"
          python -c "import os,sys,urllib.parse as u; h=u.urlparse(os.environ['DATABASE_URL']).hostname; \
if h and 'supabase.co' in h: print('ERROR: DATABASE_URL still points to Supabase. Update RW_DATABASE_URL to Railway.'); sys.exit(2)"

      - name: Connect test (DB identity)
        run: |
          python -c "import os,psycopg2 as p; c=p.connect(os.environ['DATABASE_URL']); cur=c.cursor(); \
cur.execute('SELECT current_database(), inet_server_addr();'); print('DB identity:', cur.fetchone()); c.close()"
      # ----------------------------------------------------------------------

      - name: Run Prisma → DB (UPSERT by EAN)
        run: |
          python scripts/prisma_food_scrape_to_db.py --max-products 400 --headless 1

      - name: Produce CSV export
        run: |
          python scripts/prisma_food_scraper.py --out prisma_foods.csv --max-products 400 --headless 1
          echo "CSV line count (incl header):"; wc -l prisma_foods.csv || true
          echo "Preview:"; head -n 5 prisma_foods.csv || true

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: prisma_foods.csv
          path: prisma_foods.csv
          if-no-files-found: error
