name: Prisma → Price Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # every 6h UTC

jobs:
  update-prices:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DATABASE_URL: ${{ secrets.RW_DATABASE_URL }}
      PRISMA_STORE_ID: "14"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install playwright psycopg2-binary

      - name: Install Chromium + deps
        run: python -m playwright install --with-deps chromium

      - name: Update Prisma prices
        run: python scripts/prisma_price_updater.py --max-products 500 --headless 1
