name: R2 Image Cleanup

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Preview only? (1=yes, 0=no)"
        required: true
        default: "1"
      clear_db:
        description: "Also blank products.image_url for deleted objects? (1=yes, 0=no)"
        required: true
        default: "0"
      prefix:
        description: "R2 key prefix to scan"
        required: true
        default: "products/prisma/"

jobs:
  clean:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # DB (public connection string is fine for this job)
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}
      DB_CONNECT_TIMEOUT: "10"

      # R2
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      R2_PUBLIC_BASE: ${{ secrets.R2_PUBLIC_BASE }}
      R2_PREFIX: "products/"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install boto3 psycopg2-binary

      - name: Run cleaner (DRY-RUN by default)
        run: |
          echo "Prefix: ${{ github.event.inputs.prefix }}"
          python scripts/r2_delete_unsupported.py \
            --prefix "${{ github.event.inputs.prefix }}" \
            --dry-run ${{ github.event.inputs.dry_run }} \
            --clear-db ${{ github.event.inputs.clear_db }}
