name: "Selver → Brand Enrichment (PDP, structured only)"

on:
  # Every ~90 minutes using two crons (GitHub doesn't support */90):
  # - 00 at 0,3,6,9,12,15,18,21
  # - 30 at 1,4,7,10,13,16,19,22
  schedule:
    - cron: "0 0-23/3 * * *"
    - cron: "30 1-23/3 * * *"
    # Plus a weekly Sunday sanity run at 03:29 UTC
    - cron: "29 3 * * 0"
  workflow_dispatch:
    inputs:
      max_items:
        description: "Rows to attempt this run (missing brand)"
        required: false
        default: "600"
      headless:
        description: "Headless (1/0)"
        required: false
        default: "1"
      req_delay:
        description: "Per-item delay seconds"
        required: false
        default: "0.25"
      timebox_minutes:
        description: "Soft time limit for the enrichment (minutes) — keep < job timeout"
        required: false
        default: "55"
      overwrite_products:
        description: "Overwrite existing brand in products table? (1/0)"
        required: false
        default: "0"

concurrency:
  group: selver-brand-enrich
  cancel-in-progress: true

jobs:
  brand:
    runs-on: ubuntu-latest
    # More headroom than the script timebox
    timeout-minutes: 120

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PUBLIC }}
      MAX_ITEMS: ${{ github.event.inputs.max_items || '600' }}
      HEADLESS: ${{ github.event.inputs.headless || '1' }}
      REQ_DELAY: ${{ github.event.inputs.req_delay || '0.25' }}
      TIMEBOX_MINUTES: ${{ github.event.inputs.timebox_minutes || '55' }}
      OVERWRITE_PRODUCTS: ${{ github.event.inputs.overwrite_products || '0' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright psycopg2-binary
          python -m playwright install --with-deps chromium

      - name: Sanity check script
        run: |
          test -f scripts/selver_brand_enrich_pw.py || { echo "Missing scripts/selver_brand_enrich_pw.py"; exit 1; }

      - name: Show config
        run: |
          echo "MAX_ITEMS=$MAX_ITEMS"
          echo "HEADLESS=$HEADLESS"
          echo "REQ_DELAY=$REQ_DELAY"
          echo "TIMEBOX_MINUTES=$TIMEBOX_MINUTES"
          echo "OVERWRITE_PRODUCTS=$OVERWRITE_PRODUCTS"

      - name: Run Selver Brand Enrichment (timeboxed)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          # Convert minutes→seconds for the script and soft-limit the whole step
          export TIMEBOX_SECONDS=$(( TIMEBOX_MINUTES * 60 ))

          # Soft stop at timebox, allow 120s to wrap up; treat common timeout codes as success
          set +e
          timeout --signal=SIGINT --kill-after=120s ${TIMEBOX_MINUTES}m \
            python scripts/selver_brand_enrich_pw.py
          rc=$?
          if [ $rc -eq 0 ] || [ $rc -eq 124 ] || [ $rc -eq 130 ] || [ $rc -eq 137 ]; then
            echo "Script finished with code $rc (treated as success)."
            exit 0
          else
            echo "Script failed with code $rc (real error)."
            exit $rc
          fi

      - name: Post-run stats
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client

          echo "Missing Selver candidate brands overall:"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
          SELECT COUNT(*) AS missing_brand
          FROM selver_candidates
          WHERE COALESCE(brand,'') = '';
          "

          echo "Products with brand set (any source):"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
          SELECT COUNT(*) AS products_with_brand
          FROM products
          WHERE COALESCE(brand,'') <> '';
          "

          echo "Top 15 brands (from selver_candidates) now present:"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
          SELECT brand, COUNT(*) AS cnt
          FROM selver_candidates
          WHERE COALESCE(brand,'') <> ''
          GROUP BY brand
          ORDER BY cnt DESC, brand
          LIMIT 15;
          "
