name: Selver - Seed/Backfill stores (online + physical)

on:
  workflow_dispatch:
    inputs:
      backfill_only:
        description: "Backfill only rows with missing/zero lat/lon from DB (1) or do full scrape+seed (0)"
        required: false
        default: "1"
      geocode:
        description: "Geocode with Nominatim (0/1). If 1, adds lat/lon (slower)."
        required: false
        default: "1"
      chain:
        description: "Retail chain label"
        required: false
        default: "Selver"
      online_name:
        description: "Name of online store"
        required: false
        default: "e-Selver"
      dry_run:
        description: "Dry run (0/1) - parse only, no DB writes"
        required: false
        default: "0"

concurrency:
  group: seed-selver-stores
  cancel-in-progress: true

jobs:
  seed:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      DATABASE_URL:  ${{ secrets.RW_DATABASE_URL }}
      BACKFILL_ONLY: ${{ github.event.inputs.backfill_only || '1' }}
      GEOCODE:       ${{ github.event.inputs.geocode       || '1' }}
      DRY_RUN:       ${{ github.event.inputs.dry_run       || '0' }}
      CHAIN:         ${{ github.event.inputs.chain         || 'Selver' }}
      ONLINE_NAME:   ${{ github.event.inputs.online_name   || 'e-Selver' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (Playwright + DB + HTTP + HTML parse)
        run: |
          python -m pip install --upgrade pip
          pip install playwright psycopg2-binary requests beautifulsoup4
          python -m playwright install --with-deps chromium

      - name: Sanity check script
        run: |
          test -f scripts/seed_selver_stores.py || { echo "Missing scripts/seed_selver_stores.py"; exit 1; }

      - name: Show config
        run: |
          echo "BACKFILL_ONLY=$BACKFILL_ONLY GEOCODE=$GEOCODE DRY_RUN=$DRY_RUN CHAIN=$CHAIN ONLINE_NAME=$ONLINE_NAME"

      - name: Run seeder/backfiller
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python scripts/seed_selver_stores.py

      - name: Post-run report
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          echo "Summary for chain '$CHAIN' (physical stores only):"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
            SELECT
              COUNT(*) AS total_rows,
              COUNT(*) FILTER (WHERE lat BETWEEN -90 AND 90 AND lon BETWEEN -180 AND 180) AS ok_coords,
              COUNT(*) FILTER (WHERE lat IS NULL OR lon IS NULL OR COALESCE(lat,0)=0 OR COALESCE(lon,0)=0) AS missing_or_zero
            FROM stores
            WHERE chain = '$CHAIN' AND COALESCE(is_online,false)=false;
          "
          echo "Up to 50 rows still missing coords:"
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "
            SELECT id, name, address
            FROM stores
            WHERE chain = '$CHAIN'
              AND COALESCE(is_online,false)=false
              AND (lat IS NULL OR lon IS NULL OR COALESCE(lat,0)=0 OR COALESCE(lon,0)=0)
            ORDER BY name
            LIMIT 50;
          "
