name: Vacuum Prices
on:
  schedule:
    - cron: '30 16 * * *'
jobs:
  vacuum:
    runs-on: ubuntu-latest
    steps:
      - name: Install psql
        run: sudo apt-get install -y postgresql-client
      - name: Vacuum prices table
        env:
          PGSSLMODE: require
        run: psql ${{ secrets.DATABASE_URL_PUBLIC }} -c "VACUUM ANALYZE prices;"
